Update entrypoint script to work with pachyderm helm values
pachyderm/pg-bouncer pull request #1
Opened 2022-02-09 16:39 UTC by smalyala

2022-02-09 16:49 UTC, tybritten requested changes

2022-02-09 16:49 UTC, tybritten commented on entrypoint.sh
> +    # TLS settings
ah you need to add the tls files from the tls checks here

2022-02-09 16:49 UTC, tybritten commented on entrypoint.sh
> +    ################## end file ##################
```suggestion
${PGBOUNCER_SERVER_TLS_CA_FILE:+server_tls_ca_file = ${PGBOUNCER_SERVER_TLS_CA_FILE}\n}\
${PGBOUNCER_SERVER_TLS_KEY_FILE:+server_tls_key_file = ${PGBOUNCER_SERVER_TLS_KEY_FILE}\n}\
${PGBOUNCER_SERVER_TLS_CERT_FILE:+server_tls_cert_file = ${PGBOUNCER_SERVER_TLS_CERT_FILE}\n}\
    ################## end file ##################
```

2022-02-09 17:23 UTC, tybritten commented
i think maybe we should add an 'if' to do if any of those server tls vars are set, to set the SERVER_TLS_SSLMODE

2022-02-09 18:28 UTC, smalyala commented
So something like this: `# TODO: Include SERVER_TLS_SSLMODE in the pgbouncer config only if any of the server TLS file env vars are set`

2022-02-10 15:52 UTC, tybritten approved these changes

2022-02-10 15:52 UTC, tybritten commented on entrypoint.sh
> +    ${CLIENT_TLS_SSLMODE:+client_tls_sslmode = ${CLIENT_TLS_SSLMODE}\n}\
```suggestion
```

Don't need client

2022-02-10 15:52 UTC, merged